apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - namespace.yaml
  - storage/storage.yaml
  - deployments/deployment.yaml
  - services/service.yaml
  - ingress/ingress.yaml
  - autoscaling/vpa.yaml
  - pdb/pdb.yaml
  - networkpolicy/cilium-networkpolicy.yaml
