---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    name: media
    app.kubernetes.io/part-of: jellyfin
    tls.example.com/wildcard: "true"
    goldilocks.fairwinds.com/enabled: "true"
