---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authentik-server
  namespace: authentik
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: authentik-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authentik-worker
  namespace: authentik
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: authentik-worker
