---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure-alerts.yaml
  - trivy-security-alerts.yaml
  - recording-rules.yaml
  - slo-alerts.yaml
  - security-alerts.yaml
  - media-drop-alerts.yaml
  - flux-slo.yaml
  - cilium-alerts.yaml
