apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - namespace.yaml
  - deployments/server.yaml
  - ingress/ingress.yaml
  - networkpolicy/cilium-networkpolicy.yaml
  - autoscaling/hpa.yaml
  - autoscaling/vpa.yaml
  - pdb/pdb.yaml
