---
apiVersion: v1
kind: Namespace
metadata:
  name: crowdsec
  labels:
    # CrowdSec needs privileged: agents use hostPath + root, LAPI requires root for /etc/crowdsec
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    goldilocks.fairwinds.com/enabled: "true"
