---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-data
  namespace: docmost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-postgresql
  namespace: docmost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-csi
  resources:
    requests:
      storage: 5Gi
