---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-data
  namespace: gitlab-runner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
