---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - traefik.yaml
  - traefik-dmz.yaml
  - authentik.yaml
  - postgresql.yaml
  - redis.yaml
  - flux-podmonitor.yaml
  - media-drop-watcher.yaml
