apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - deployments/deployment.yaml
  - ingress/ingress.yaml
  - ingress/middleware.yaml
  - namespace.yaml
  - rbac/rbac.yaml
  - rbac/serviceaccount.yaml
  # Secrets managed by infrastructure/secrets repo
  - services/service.yaml
  - autoscaling
  - pdb/pdb.yaml
