# Application: Authentik
# Version: 2025.10.1
# Updated: 2025-11-13
# Source: https://github.com/goauthentik/authentik/releases
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: authentik
  labels:
    app: authentik-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik-worker
  template:
    metadata:
      labels:
        app: authentik-worker
    spec:
      serviceAccountName: authentik
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: authentik
        image: ${IMAGE_AUTHENTIK}
        imagePullPolicy: IfNotPresent
        args:
        - worker
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        env:
        - name: AUTHENTIK_REDIS__HOST
          value: authentik-redis
        - name: AUTHENTIK_POSTGRESQL__HOST
          value: authentik-postgresql
        - name: AUTHENTIK_POSTGRESQL__NAME
          value: authentik
        - name: AUTHENTIK_POSTGRESQL__USER
          value: authentik
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: AUTHENTIK_POSTGRESQL__PASSWORD
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: AUTHENTIK_SECRET_KEY
        - name: AUTHENTIK_ERROR_REPORTING__ENABLED
          value: "false"
        - name: AUTHENTIK_LOG_LEVEL
          value: info
        resources:
          # Managed by VPA (authentik-worker) - Auto mode, range: 100m-1 cpu, 640Mi-2Gi mem
          requests:
            cpu: 100m
            memory: 640Mi
          limits:
            memory: 1Gi
