---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner
  labels:
    name: gitlab-runner
    # Must match infrastructure/psa-labels/psa-labels.yaml
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
    goldilocks.fairwinds.com/enabled: "true"
