---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls-cert
  namespace: monitoring
spec:
  secretName: prometheus-tls-cert
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
  dnsNames:
    - metrics.example.com
