---
apiVersion: v1
kind: Service
metadata:
  name: docmost
  namespace: docmost
  labels:
    app.kubernetes.io/name: docmost
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: docmost
