apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authentik.yaml
- automation.yaml
- cert-manager.yaml
- cloudflared.yaml
- democratic-csi.yaml
- docmost.yaml
- external-dns.yaml
- gitlab-runner.yaml
- headlamp.yaml
- karpenter.yaml
- mcp-server.yaml
- media.yaml
- monitoring.yaml
- semaphore.yaml
- unifi.yaml
- vaultwarden.yaml
- velero.yaml
- vm-certificates.yaml
- vpn.yaml
