---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    app: grafana
    grafana_datasource: "true"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 15s
          httpMethod: POST
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.loki.svc.cluster.local:3100
        editable: true
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: prometheus
              matcherRegex: "pod=([^\\s]+)"
              name: Pod
              url: '/explore?left={"queries":[{"refId":"A","expr":"{pod=\"$${__value.raw}\"}"}]}'
