---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
  labels:
    # Privileged required for node-agent DaemonSet (hostPath volumes, privileged containers)
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
    goldilocks.fairwinds.com/enabled: "true"
