---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - deployment.yaml
  - secret.yaml
  - servicemonitor.yaml

labels:
  - pairs:
      app.kubernetes.io/name: mktxp
      app.kubernetes.io/component: exporter
