---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-backups
  namespace: semaphore
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
