---
- name: Restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
  become: true

- name: Reload haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
  become: true

- name: Restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
  become: true
