---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ntfy

resources:
  - namespace.yaml
  - deployments/deployment.yaml
  - services/service.yaml
  - ingress/ingress.yaml
  - storage/pvc.yaml
  - autoscaling

labels:
  - pairs:
      app.kubernetes.io/name: ntfy
      app.kubernetes.io/component: notifications
