---
apiVersion: v1
kind: Namespace
metadata:
  name: ntfy
  labels:
    app.kubernetes.io/name: ntfy
    tls.example.com/wildcard: "true"
    # Must match infrastructure/psa-labels/psa-labels.yaml
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    goldilocks.fairwinds.com/enabled: "true"
