apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: authentik
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: automation
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: cert-manager
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: cloudflared
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: gitlab-runner
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: headlamp
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: karpenter
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: semaphore
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: vaultwarden
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: velero
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: vm-certificates
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: netbox
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: core
  name: credential-core
  namespace: mcp-server
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: media
  name: credential-media
  namespace: mcp-server
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: monitoring
  name: credential-monitoring
  namespace: mcp-server
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: network
  name: credential-network
  namespace: mcp-server
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: media
  name: credential-media
  namespace: media
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: media
  name: credential-media
  namespace: docmost
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: media
  name: credential-media
  namespace: matrix
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: monitoring
  name: credential-monitoring
  namespace: monitoring
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: storage
  name: credential-storage
  namespace: democratic-csi
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: storage
  name: credential-storage
  namespace: storage
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: network
  name: credential-network
  namespace: external-dns
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: network
  name: credential-network
  namespace: vpn
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.kubernetes.io/managed-by: external-secrets
    credential-ssot.example.com/domain: network
  name: credential-network
  namespace: unifi
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-store
      remoteNamespace: flux-system
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
