---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - license-policy.yaml
  - license-scan-cronjob.yaml

labels:
  - pairs:
      app.kubernetes.io/component: sbom-manager
      app.kubernetes.io/part-of: security
