---
- name: Create GitLab directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ gitlab_config_dir }}"
    - "{{ gitlab_config_dir }}/ssl"
    - "{{ gitlab_logs_dir }}"
    - "{{ gitlab_data_storage }}"
  become: true
  tags:
    - gitlab

- name: Deploy GitLab docker-compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ gitlab_data_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  become: true
  tags:
    - gitlab
    - config

- name: Start GitLab containers
  community.docker.docker_compose_v2:
    project_src: "{{ gitlab_data_dir }}"
    state: present
    pull: missing
  become: true
  tags:
    - gitlab
