---
# VPA for karpenter proxmox provider
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: karpenter
  namespace: karpenter
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: karpenter-karpenter-provider-proxmox
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: karpenter-provider-proxmox
        minAllowed:
          cpu: 50m
          memory: 128Mi
        maxAllowed:
          cpu: 500m
          memory: 512Mi
